-- ИНСТРУКЦИЯ:
-- 1. Скопируйте этот код.
-- 2. Перейдите в Supabase Dashboard -> SQL Editor.
-- 3. Вставьте код и нажмите "Run".

-- 1. Создаем таблицу 'evaluations' для хранения истории проверок
create table if not exists public.evaluations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null, -- Ссылка на пользователя (требуется авторизация)
  essay_text text not null,                    -- Текст сочинения
  result_data jsonb not null                   -- Результат проверки от ИИ (JSON)
);

-- 2. Включаем защиту данных (RLS - Row Level Security)
-- Это гарантирует, что к таблице нельзя получить доступ без соответствующих прав
alter table public.evaluations enable row level security;

-- Удаляем старые политики перед созданием новых (для идемпотентности скрипта)
drop policy if exists "Users can insert their own evaluations" on public.evaluations;
drop policy if exists "Users can view their own evaluations" on public.evaluations;

-- 3. Создаем правила доступа

-- Правило: Пользователь может сохранять только свои проверки
create policy "Users can insert their own evaluations"
  on public.evaluations for insert
  with check (auth.uid() = user_id);

-- Правило: Пользователь может видеть только свои проверки
create policy "Users can view their own evaluations"
  on public.evaluations for select
  using (auth.uid() = user_id);

-- 4. Создаем индекс для оптимизации сортировки по дате (ускоряет загрузку истории)
create index if not exists evaluations_user_id_created_at_idx on public.evaluations (user_id, created_at desc);
