-- ============================================================================
-- REFINED QUILL - ПОЛНАЯ НАСТРОЙКА БЕЗОПАСНОСТИ SUPABASE
-- ============================================================================
-- Инструкция:
-- 1. Скопируйте этот код
-- 2. Перейдите в Supabase Dashboard -> SQL Editor
-- 3. Вставьте и нажмите "Run"
-- ============================================================================

-- ============================================================================
-- 1. ТАБЛИЦА ПРОФИЛЕЙ ПОЛЬЗОВАТЕЛЕЙ
-- ============================================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  free_checks int default 3,
  total_checks int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Индексы для производительности
create index if not exists profiles_id_idx on public.profiles (id);
create index if not exists profiles_created_at_idx on public.profiles (created_at desc);

-- Включаем RLS
alter table public.profiles enable row level security;

-- Политики для profiles
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Service role can manage profiles" on public.profiles;

create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

create policy "Service role can manage profiles"
  on public.profiles for all
  using (auth.role() = 'service_role');

-- Триггер для автоматического создания профиля при регистрации
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, free_checks, total_checks)
  values (new.id, new.email, 3, 0);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================================================
-- 2. ТАБЛИЦА ИСТОРИИ ПРОВЕРОК (EVALUATIONS)
-- ============================================================================

create table if not exists public.evaluations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references profiles(id) on delete cascade not null,
  essay_text text not null,
  result_data jsonb not null
);

-- Индексы для производительности
create index if not exists evaluations_user_id_idx on evaluations (user_id);
create index if not exists evaluations_created_at_idx on evaluations (created_at desc);
create index if not exists evaluations_user_id_created_at_idx on evaluations (user_id, created_at desc);

-- Включаем RLS
alter table public.evaluations enable row level security;

-- Политики для evaluations
drop policy if exists "Users can insert their own evaluations" on public.evaluations;
drop policy if exists "Users can view their own evaluations" on public.evaluations;
drop policy if exists "Users can delete their own evaluations" on public.evaluations;
drop policy if exists "Service role can manage evaluations" on public.evaluations;

create policy "Users can insert their own evaluations"
  on public.evaluations for insert
  with check (auth.uid() = user_id);

create policy "Users can view their own evaluations"
  on public.evaluations for select
  using (auth.uid() = user_id);

create policy "Users can delete their own evaluations"
  on public.evaluations for delete
  using (auth.uid() = user_id);

create policy "Service role can manage evaluations"
  on public.evaluations for all
  using (auth.role() = 'service_role');

-- ============================================================================
-- 3. ФУНКЦИИ ДЛЯ ОГРАНИЧЕНИЙ
-- ============================================================================

-- Функция для ограничения количества проверок (опционально)
create or replace function public.check_free_checks()
returns trigger as $$
declare
  user_free_checks int;
begin
  select free_checks into user_free_checks
  from public.profiles
  where id = new.user_id;
  
  if user_free_checks <= 0 then
    raise exception 'Лимит бесплатных проверок исчерпан';
  end if;
  
  -- Уменьшаем счётчик бесплатных проверок
  update public.profiles
  set free_checks = free_checks - 1,
      total_checks = total_checks + 1
  where id = new.user_id;
  
  return new;
end;
$$ language plpgsql security definer;

-- ============================================================================
-- 4. БЕЗОПАСНОСТЬ AUTH.USERS (ДОПОЛНИТЕЛЬНО)
-- ============================================================================

-- Ограничиваем чтение данных пользователей
alter table auth.users enable row level security;

drop policy if exists "Users can view own auth data" on auth.users;
create policy "Users can view own auth data"
  on auth.users for select
  using (auth.uid() = id);

-- ============================================================================
-- 5. ОЧИСТКА ДАННЫХ (ОПЦИОНАЛЬНО - ДЛЯ ТЕСТИРОВАНИЯ)
-- ============================================================================

-- Функция для очистки старых данных (требует service_role)
create or replace function public.cleanup_old_evaluations(days_to_keep int default 30)
returns void as $$
begin
  delete from public.evaluations
  where created_at < now() - (days_to_keep || ' days')::interval;
end;
$$ language plpgsql security definer;

-- ============================================================================
-- 6. ПРОВЕРКА НАСТРОЕК
-- ============================================================================

-- Запрос для проверки политик RLS
-- select schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
-- from pg_policies
-- where schemaname = 'public'
-- order by tablename, policyname;

-- Запрос для проверки таблиц
-- select table_name, table_type
-- from information_schema.tables
-- where table_schema = 'public'
-- order by table_name;

-- ============================================================================
-- ГОТОВО! Безопасность настроена.
-- ============================================================================
